name: wall_clod
description: Wallpaper Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1
author: Aesthetic Developers
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.3
#interactive bottom navigation bar
  bubble_bottom_bar: ^1.2.0
#support for overlay, make it easy to build toast and In-App notification.
  overlay_support: ^1.0.4
#changing the Home Screen, Lock Screen (or both) Wallpaper(s) on Android devices
  wallpaper_manager:
#A Flutter plugin for Android and iOS supports cropping images.
  image_cropper: ^1.4.1
#Wraps platform-specific persistent storage for simple data
  shared_preferences:
#launching a URL
  url_launcher:
#A Flutter staggered grid view which supports multiple columns with rows of varying sizes.
  flutter_staggered_grid_view:
#Compact representation of a placeholder for an image.
  flutter_blurhash:
#A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider:
#gesture detector for Flutter
  simple_gesture_detector:
#show images from the internet and keep them in the cache directory
  cached_network_image:
#allows Flutter apps to discover network connectivity and configure themselves accordingly.
#It can distinguish between cellular vs WiFi connection.
  connectivity_plus: ^1.1.0
#utility library that checks for an internet connection
  data_connection_checker:
#provides with toast messages that appears in bottom of screen
  fluttertoast:
# provide some cool, animated progress indicators
  progress_indicators:
# An image library for showing placeholders and transform your image( use with  CachedNetworkImage)
  octo_image:
# to create animations in Splash Screen
  animated_splash_screen: ^1.1.0
# To connect the feedback form to firebase and store it
  cloud_firestore: ^2.5.2
  firebase_core: ^1.0.3
# create a circular profile picture in About Developers
  circular_profile_avatar: ^2.0.5
# Icons for the application.
  font_awesome_flutter: ^8.2.0
# Download or save images to gallery
  image_gallery_saver:
  dio:
  permission_handler:
  path_provider:
# Share the Application through Whatsapp or other sites.
  share: any
#payment gateways plugin
  razorpay_flutter: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/helpdesk.png
    - assets/images/information.png
    - assets/images/star.png
    - assets/images/about.png
    - assets/appIcon/1024.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
